export const plans = [
  {
    id: "residential-home-25",
    name: "Streetwise Home",
    audience: "residential",
    priceUsd: 25,
    billingPeriod: "month",
    dataGb: null,
    hotspotIncluded: true,
    coverageCountry: "US",
    provider: null,
    providerBundle: null,
    status: "planned",
    description: "Residential target plan at $25/month. Data and hotspot are intended to be included, but final allowance, throttling, hotspot limits, provider mapping, taxes, and launch terms remain subject to written provider approval and commercial validation."
  },
  {
    id: "business-starter-20",
    name: "Streetwise Business Starter",
    audience: "commercial",
    priceUsd: 20,
    billingPeriod: "month",
    dataGb: null,
    hotspotIncluded: true,
    coverageCountry: "US",
    provider: null,
    providerBundle: null,
    status: "planned",
    description: "Commercial starter target at $20/month per line. Data and hotspot are intended to be included, subject to provider approval, final usage limits, taxes, support obligations, and unit-economics validation."
  },
  {
    id: "business-volume-15",
    name: "Streetwise Business Volume",
    audience: "commercial",
    priceUsd: 15,
    billingPeriod: "month",
    minimumLines: 3,
    priceBasis: "per-line",
    dataGb: null,
    hotspotIncluded: true,
    coverageCountry: "US",
    provider: null,
    providerBundle: null,
    status: "planned",
    description: "Commercial volume target at $15/month per line for 3 or more lines. Data and hotspot are intended to be included, subject to provider approval, final usage limits, taxes, support obligations, and unit-economics validation."
  },
  {
    id: "business-pro-30",
    name: "Streetwise Business Pro",
    audience: "commercial",
    priceUsd: 30,
    billingPeriod: "month",
    priceBasis: "per-line",
    dataGb: null,
    hotspotIncluded: true,
    coverageCountry: "US",
    provider: null,
    providerBundle: null,
    status: "planned",
    description: "Higher-service commercial target at $30/month per line. Final features, data allowance, hotspot limits, support level, provider mapping, and commercial terms remain subject to written provider approval and economics validation."
  }
];
