export const plans = [
  {
    id: "residential-home-25",
    name: "Streetwise Home",
    audience: "residential",
    priceUsd: 25,
    billingPeriod: "month",
    dataGb: null,
    hotspotIncluded: true,
    coverageCountry: "US",
    provider: null,
    providerBundle: null,
    status: "planned",
    serviceModel: "cellular-mvno",
    plannedCapabilities: [
      "mobile-data",
      "hotspot",
      "voice",
      "sms",
      "local-number",
      "security-controls",
      "emergency-connectivity-reserve",
      "international-options"
    ],
    description: "Residential cellular target at $25/month. Data, hotspot, voice, SMS, local-number support, security controls, emergency-connectivity features, network options, allowances, throttling, taxes, and launch terms remain subject to written provider approval, technical implementation, regulatory allocation, and commercial validation."
  },
  {
    id: "business-starter-20",
    name: "Streetwise Business Starter",
    audience: "commercial",
    priceUsd: 20,
    billingPeriod: "month",
    dataGb: null,
    hotspotIncluded: true,
    coverageCountry: "US",
    provider: null,
    providerBundle: null,
    status: "planned",
    serviceModel: "cellular-mvno",
    plannedCapabilities: [
      "mobile-data",
      "hotspot",
      "voice",
      "sms",
      "local-number",
      "multi-line-management",
      "security-controls"
    ],
    description: "Commercial cellular starter target at $20/month per line. Final voice, SMS, number, data, hotspot, security, network, support, tax, and lifecycle capabilities require provider approval and unit-economics validation."
  },
  {
    id: "business-volume-15",
    name: "Streetwise Business Volume",
    audience: "commercial",
    priceUsd: 15,
    billingPeriod: "month",
    minimumLines: 3,
    priceBasis: "per-line",
    dataGb: null,
    hotspotIncluded: true,
    coverageCountry: "US",
    provider: null,
    providerBundle: null,
    status: "planned",
    serviceModel: "cellular-mvno",
    plannedCapabilities: [
      "mobile-data",
      "hotspot",
      "voice",
      "sms",
      "local-number",
      "multi-line-management"
    ],
    description: "Commercial volume target at $15/month per line for 3 or more lines. This is a planning price, not a sellable offer. Final cellular capabilities and economics require a mapped wholesale product and written commercial approval."
  },
  {
    id: "business-pro-30",
    name: "Streetwise Business Pro",
    audience: "commercial",
    priceUsd: 30,
    billingPeriod: "month",
    priceBasis: "per-line",
    dataGb: null,
    hotspotIncluded: true,
    coverageCountry: "US",
    provider: null,
    providerBundle: null,
    status: "planned",
    serviceModel: "cellular-mvno",
    plannedCapabilities: [
      "mobile-data",
      "hotspot",
      "voice",
      "sms",
      "local-number",
      "number-porting",
      "multi-line-management",
      "security-controls",
      "network-resilience-options",
      "international-options"
    ],
    description: "Higher-service commercial cellular target at $30/month per line. Final network, voice/SMS, number-porting, security, roaming, hotspot, support, and SLA capabilities remain subject to provider contract, implementation, testing, and economics validation."
  }
];
